聖洋科技面試考題


請你用spring boot + gradle 做一個web service (盡量以Java8 語法實作)

 
功能1. 每分鐘打一次下面的api 取得Json內容回來存到DB

https://beta-ssp.tenmax.io/supply/mobile/native/rmax-ad?rmaxSpaceId=55ba76bca772421f&dpid=bd4b9b7903cf40ce&v=1
 

回傳的內容應該會如下，這是我們native ad 的廣告內容，重點是 title , description, image url, icon url , impression link 和 click url。

=====================================================

{
  "native": {
    "viewEvent": [
      "https://dev2.tenmax.io/smaato2/bid/asiamax/viewable/1469773959404/3eff5c90-5556-11e6-bce2-c3cd4b72e6ab/3690/5560/bd4b9b7903cf40ce/"
    ], 
    "link": {
      "url": "https://dev2.tenmax.io/smaato2/bid/asiamax/click/1469773959404/3eff5c90-5556-11e6-bce2-c3cd4b72e6ab/3690/5560/?rUrl=http%3A%2F%2Fgoo.gl%2FqgL83s%3Ftmax_click_id%3D3eff5c90-5556-11e6-bce2-c3cd4b72e6ab%26tmax_space_id%3Dc145f1cd389e49a5%26tmax_adx_id%3Dasiamax&sUrl=http%3A%2F%2Fbeta-ssp.tenmax.io%2Fauction%2Fwinner%2Ftracking%2Fclk%3Fb%3D3eff5c90-5556-11e6-bce2-c3cd4b72e6ab%26i%3D0%26adurl%3D%26id%3Ddb0efe1b-8522-45f8-a460-86bf42e3e3b8", 
      "clicktrackers": []
    }, 
    "assets": [
      {
        "id": 1, 
        "title": {
          "text": "\u4f4e\u8abf\u8b8a\u7f8e\uff01\u9084\u59b3\u539f\u751f\u808c\u819a\uff0c\u4ee3\u50f9\u9084\u76f8\u7576\u4fbf\u5b9c\uff1f"
        }
      }, 
      {
        "id": 2, 
        "img": {
          "url": "//tenmaximg.cacafly.net/upload/5/5/6/0/0b11472c_icon.png?v=1", 
          "h": 250, 
          "w": 250
        }
      }, 
      {
        "id": 3, 
        "img": {
          "url": "//tenmaximg.cacafly.net/upload/5/5/6/0/0b11472c_m.png?v=1", 
          "h": 300, 
          "w": 574
        }
      }, 
      {
        "data": {
          "value": "\u6216\u8a31\u4f60\u5df2\u7d93\u7fd2\u6163\u7528\u5316\u599d\u84cb\u6389\u6591\u9ede\uff0c\u4f46\u590f\u5b63\u51fa\u9580\u4e00\u5c64\u5c64\u5be6\u5728\u592a\u4e0d\u8212\u670d\uff01\u60f3\u505a\u6de8\u819a\u96f7\u5c04\uff0c\u9019\u5b63\u7bc0\u6211\u5011\u53c8\u8a72\u6ce8\u610f\u54ea\u4e9b\u8853\u5f8c\u7167\u8b77\u5462\uff1f"
        }, 
        "id": 4
      }, 
      {
        "link": {
          "url": "http://goo.gl/qgL83s", 
          "clicktrackers": []
        }, 
        "data": {
          "value": "\u6de8\u598d\u91ab\u7f8e\u76e1\u662f\u70ba\u59b3"
        }, 
        "id": 5
      }, 
      {
        "id": 6, 
        "img": {
          "url": "//tenmaximg.cacafly.net/upload/5/5/6/0/0b11472c.png?v=1", 
          "h": 627, 
          "w": 1200
        }
      }, 
      {
        "id": 7, 
        "img": {
          "url": "//tenmaximg.cacafly.net/upload/5/5/6/0/0b11472c_s.png?v=1", 
          "h": 150, 
          "w": 287
        }
      }, 
      {
        "id": 8, 
        "img": {
          "url": "//tenmaximg.cacafly.net/upload/5/5/6/0/0b11472c_icon_l.png?v=1", 
          "h": 627, 
          "w": 627
        }
      }, 
      {
        "id": 9, 
        "img": {
          "url": "//tenmaximg.cacafly.net/upload/5/5/6/0/0b11472c_icon_s.png?v=1", 
          "h": 80, 
          "w": 80
        }
      }
    ], 
    "impressionEvent": [
      "//beta-ssp.tenmax.io/supply/tracking/pixel?s=3eff5c90-5556-11e6-bce2-c3cd4b72e6ab&r=c145f1cd389e49a5", 
      "//beta-ssp.tenmax.io/auction/winner/tracking/pixel?b=3eff5c90-5556-11e6-bce2-c3cd4b72e6ab&i=0&id=db0efe1b-8522-45f8-a460-86bf42e3e3b8", 
      "https://dev2.tenmax.io/smaato2/bid/asiamax/impreWithPrice/1469773959404/3eff5c90-5556-11e6-bce2-c3cd4b72e6ab/3690/5560/bd4b9b7903cf40ce/xlKZgilSOsdwe7s/"
    ]
  }
}
=========================================

 

2. 資料抓回來後，請你設計一個簡單的ORM model 來儲存抓回來資訊 (DB請用 in memory db 如 h2)

(請把title 設定為 unique key)


3. 實作一個rest api 可以從資料庫撈出這些資料 (query by title 可以模糊比對)

如有任何問題，歡迎討論
 
請提供原始碼(可以放到github 上之類) 